name: Build Helix
on:
  push:
    paths:
      - 'repo/Containerfile.helix'
  workflow_dispatch:
jobs:
  call-reusable-build:
    permissions:
      packages: write
      contents: read
    uses: ./.github/workflows/reusable-build.yml
    with:
      name: 'helix'